language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "StockPortfolio-test";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: andys-ez-stocks
  api_key: d684b429-a468-4cc1-910e-580de5e106d9
